# Generated by Django 3.2.7 on 2021-09-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimages',
            options={'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='', upload_to='project/image'),
        ),
    ]
