# Generated by Django 3.2.7 on 2022-04-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
