# Generated by Django 3.2.7 on 2021-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210920_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_link',
            field=models.CharField(default='', max_length=250),
        ),
    ]
